italia/spid-testenv2

spid-testenv.py

#8: Better users file handling

---

spid-testenv.py

Aggiunto endpoint per generare il metadata dell'IdP automaticamente (issue di riferimento: #17 )

Add endpoint to fetch IdP metadata

---

.gitignore
README.md
ansible/README.md
config.yaml.example
sp_metadata.xml.example

Ho rivisto il README per renderlo più chiaro ed ho riordinato e commentato il file di configurazione in modo da dare all'utente visione immediata di dove deve mettere le mani.
Ho anche aggiunto un template di metadati SP per tamponare l'assenza di uno strumento di compilazione assistita.

Miglioramenti al README e alla configurazione

---

spid-testenv.py

Provide RelayState in slo response

---

conf/config.yaml.example
testenv/server.py
testenv/tests/data/config.yaml

Rename 'hostname' in 'base_url' and related fixes to flow

---

testenv/saml.py
testenv/tests/test_saml.py

Fix missing Issuer

---

testenv/server.py
testenv/tests/test_spid_testenv.py
testenv/users.py

Add proper prefix to fiscal number field. Fix issue #150

---

testenv/tests/data/sample_saml_requests.py
testenv/tests/test_spid_testenv.py
testenv/tests/test_validators.py
testenv/validators.py

Fix check on Destination attribute on requests. Fix issue #158

---

testenv/crypto.py

Fix regression causing bad signatures because of the xml-c14n11 canonicalization method

---

testenv/saml.py
testenv/tests/test_saml.py

Add SessionIndex in Response. Fix issue #160

---

testenv/crypto.py
testenv/settings.py
testenv/tests/test_crypto.py
testenv/tests/test_spid_testenv.py
testenv/tests/utils.py

More coverage on crypto module

---

testenv/tests/data/sample_saml_requests.py
testenv/tests/test_spid_testenv.py
testenv/tests/test_validators.py
testenv/validators.py

Improve and some minor fixes on SpidValidator. Fix issue #159 #165

---

testenv/saml.py

@alexrj 
Fixes #182 due to an  undefined variable
Replace  s/ascs/_ascs/ fixes.

Fix: #182. Undefined variable.

---

testenv/server.py
testenv/spmetadata.py
testenv/tests/test_spid_testenv.py
testenv/utils.py
testenv/validators.py

Fix regression causing LogoutRequest messages to generate an error.

---

testenv/parser.py
testenv/spmetadata.py
testenv/tests/test_parsers.py
testenv/tests/test_validators.py

Fix xml declaration handling. Fix issue #146

---

spid-testenv.py
testenv/crypto.py
testenv/exceptions.py
testenv/parser.py
testenv/saml.py
testenv/server.py
testenv/settings.py
testenv/spmetadata.py
testenv/tests/data/sp-metadata.xml.example
testenv/tests/test_spid_testenv.py
testenv/tests/test_validators.py
testenv/tests/utils.py
testenv/utils.py
testenv/validators.py

Validate metadata

---

templates/login.html
testenv/saml.py
testenv/server.py

Handle custom response

---

testenv/settings.py
testenv/tests/data/sp-metadata.xml.example

Relativo a https://github.com/italia/spid-testenv2/issues/199
@fmarco ti sarà sfuggito :+1: 
ho effettuato i test, sembra tutto k

countyOfBirth fixed in countryOfBirth

---

testenv/settings.py
testenv/tests/data/sp-metadata.xml.example

county is correct
https://www.agid.gov.it/sites/default/files/repository_files/regole_tecniche/tabella_attributi_idp_v1_0.pdf

fix typo country=>county

---

testenv/server.py

Fixes
https://github.com/italia/spid-testenv2/issues/237

[bugfix] str decode exception

---

conf/config.yaml.example
testenv/spmetadata.py

Support globbing in metadata/local pathnames.

---

Dockerfile
README.md
entrypoint.sh

Autogenerate the key and certificate in Docker if they don't
exist.

Autogenerate the key and certificate in Docker.

---

testenv/storages.py

Make spidCode match the standard defined format.

---

testenv/config.py

Fix metadata key's type in the config file.

---

requirements.in
requirements.txt
testenv/storages.py
testenv/tests/test_storages.py

Generate valid fiscal codes when no users.json is available.
Fix #209.

Generate valid fiscal codes.

---

templates/login.html

Fix input overlapping with label in login.

---

templates/home.html
testenv/server.py
testenv/spmetadata.py
testenv/tests/test_spid_testenv.py
testenv/tests/test_validators.py
testenv/validators.py

Revert the commit from PR #279 as it causes problems with
metadata from the database.
This reverts commit f3fd0b1a84859c998168cea900ac335aae5374bb.

Revert "Refactor the SP metadata loading logic."

---

README.md
conf/config.yaml.example

Some general usage note about Postgres and sqlalchemy.
A better config example with a local metadata  as default configuration

Minor changes in README and example config
